export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
       <body>
      <header style={{
        backgroundColor:'lightblue',
        padding: '1rem'
      }}>
        <p>Header</p>
      </header>
     {children}
      <footer style={{
        backgroundColor:'lightgray',
        padding: '1rem'
      }}>
        <p>�� 2024 My Website. All rights reserved.</p>
      </footer>
      </body>
    </html>
  )
}
